### ISSUE TITLE
hanami db create getting error

### ISSUE THREAD

**Issue by sbusso** [TurfMedia/html2pdf#7]
`block in create': No such file or directory - createdb (Hanami::Model::MigrationError)

**Comment by sbusso** [comment]
see branch dockerize

**Comment by valexl** [comment]
Here is what I get when asking about this issue 

```That is by design. Creating a database in production is something you should do outside of the framework. In case of Heroku, you should use their CLI.
https://devcenter.heroku.com/articles/heroku-postgresql#create-a-new-database
```

**Comment by sbusso** [comment]
the pb is not in prod but in dev

**Comment by sbusso** [comment]
fixed https://github.com/TurfMedia/html2pdf/commit/c6e5b202d3b71d3dad38ea34f1a88f02fab2639e
